albercan_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pet.urls', namespace='pet')),
    path('', include('people.urls', namespace='people')),
    path('auth/', include('authentication.urls', namespace='authentication')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from authentication.forms import UserLoginForm

app_name = "authentication"
urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="authentication/login_page.html", form_class=UserLoginForm
        ),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
]

pet/urls.py
from django.urls import path

from pet.views import main_page

app_name = 'pet'
urlpatterns = [
    path("index/", main_page, name="main_page"),
]

albercan_backend/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Animate CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
          integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Title -->
    <title>{% block title %}AlberCan{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/31b739dec4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static "css/base.css" %}>
    <link rel="stylesheet" href={% static "css/navbar.css" %}>
    <!-- Additional Styling -->
    {% block styles %}{% endblock %}
  </head>
  <body>
    <header>
      {% include "navbar.html" %}
    </header>
    <!-- Main Content -->
    <main>
      {% block content %}
      {% endblock %}
    </main>
    {% block scripts %}{% endblock %}
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous">
    </script>
  </body>
</html>

albercan_backend/templates/navbar.html
<!-- navbar.html -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'pet:main_page' %}">AlberCan</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto pl-lg-5 pl-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            Más Info
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Mascotas en Adopción</a></li>
            <li><a class="dropdown-item" href="#">Mascotas rescatadas</a></li>
            <li><a class="dropdown-item" href="#">Como Ayudar</a></li>
            <li><a class="dropdown-item" href="#">Nuestra Misión</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Testimonios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contáctanos</a>
        </li>
        <li class="nav-item">
          {% if request.user.is_authenticated %}
          <form id="logout-form" method="post" action="{% url 'authentication:logout' %}">
            {% csrf_token %}
            <button type="submit" class="nav-link">Cerrar Sesión</button>
          </form>
          {% else %}
            <a class="nav-link" href="{% url 'authentication:login' %}">Iniciar Sesión</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>